<a href="https://colab.research.google.com/github/Aryangajbhare2002/Unified-/blob/main/Pandas_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [ ]:
import pandas as pd
import numpy as npy

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [4]:
a = pd.Series([100,200,300,400])

a

0    100
1    200
2    300
3    400
dtype: int64

Print a, and data type

In [8]:
a
type(a)

pandas.core.series.Series

Using indexing access the element 300 from the series a.

In [9]:
pd.Series(a)[2]

np.int64(300)

What are the values of index for series a?

In [10]:
pd.Series(a).index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [16]:
a.index = ['c','a','b','d']
a

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [17]:
print(a["d"])

400

Sort the values wrt to the index and print it

In [20]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [21]:
 b = pd.Series([800,450,100],index=["e","f","g"])

b

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [23]:
 k= pd.concat([a,b])
k

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

In [24]:
#print a again after appending b into it

k

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [31]:
o = a.sort_values(ascending=True)
o

c    100
a    200
b    300
d    400
dtype: int64

In [32]:
k.sort_values()

c    100
g    100
a    200
b    300
d    400
f    450
e    800
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [35]:
df = pd.DataFrame({'num':[100,200,300]})
df

   num
0  100
1  200
2  300

What is the shape of the datafarme <br>
(also, what does it imply?)

In [41]:
df.shape
Df.shape

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [ ]:
# yep its same as the series.

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [43]:
print(df.head)
print(df.tail)
print(Df.head)
print(Df.tail)

<bound method NDFrame.head of    num
0  100
1  200
2  300>
<bound method NDFrame.tail of    num
0  100
1  200
2  300>
<bound method NDFrame.head of      0
c  100
a  200
b  300
d  400
e  800
f  450
g  100>
<bound method NDFrame.tail of      0
c  100
a  200
b  300
d  400
e  800
f  450
g  100>

Rename the column of the dataframe as 'points'

In [46]:
points = df.rename(columns={"num":'points'})
points

   points
0     100
1     200
2     300

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [49]:
#Create fruits array

fruits =pd.DataFrame({'Fruits':['orange','mango','apple','jackfruit','cherry','pineapple','watermelon']})

fruits

       Fruits
0      orange
1       mango
2       apple
3   jackfruit
4      cherry
5   pineapple
6  watermelon

In [50]:
#Create series fruits out of fruits array

fruits2 =pd.Series(['kivi','chikoo','Banana','Guava'])
fruits2

0      kivi
1    chikoo
2    Banana
3     Guava
dtype: object

Change the index of fruits to the index of dataframe df

In [51]:

pd.Series(fruits2,index=points.index)

0      kivi
1    chikoo
2    Banana
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [58]:
fruits_aligned = pd.Series(fruits2.values[:len(points.index)], index=points.index)
points['fruits'] = fruits_aligned
print(points.head())

   points  fruits
0     100    kivi
1     200  chikoo
2     300  Banana

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [62]:
d1 = ({'city':['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali' ], 'temperature':[15, 22, 20, 26,-2]})

d1 = pd.DataFrame(d1)
d1

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

Print(d1)

In [63]:
print(d1)

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [65]:
shape = d1.shape
shape

(5, 2)

Set city = d1['city']

In [66]:
city = d1['city']

print city <br>
What is the type of city.

In [67]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [68]:
d2 =({'city': ['Bengalaru','Coimbatore','Srirangam','Pondicherry'], 'temperature':[24,35,36,39]})
d2=pd.DataFrame(d2)
d2

          city  temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [69]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [72]:
d3 = pd.concat([d1,d2])
d3

          city  temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [78]:
A= d3.loc[d3['temperature'] <= 20, 'city']
print(A)
print(f"Number of cities: {len(A)}")

0    Chandigarh
2        Kanpur
4        Manali
Name: city, dtype: object
Number of cities: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [79]:
B=d3.loc[d3['temperature']>=35]
print(B)

          city  temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [80]:
def is_ut(city):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return city in union_territories

d3['is_ut'] = d3['city'].apply(is_ut)

In [81]:
print(d3)

          city  temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [82]:
def c_to_f(temp_c):
    return (temp_c * 9/5) + 32

In [83]:
print(c_to_f(10))

50.0

In [84]:
d3['temp_farenhiet'] = d3['temperature'].apply(c_to_f)
print(d3)

          city  temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
0    Bengalaru           24  False            75.2
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [85]:
union_territory_cities_d3 = d3[d3['is_ut']]
print(union_territory_cities_d3)

          city  temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
3  Pondicherry           39   True           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [86]:
cities_above_90F = d3[d3['temp_farenhiet'] > 90]
print(cities_above_90F)

          city  temperature  is_ut  temp_farenhiet
1   Coimbatore           35  False            95.0
2    Srirangam           36  False            96.8
3  Pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [87]:
print(d1.head(3))

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [88]:
print(d3.iloc[:, -2:])

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
0  False            75.2
1  False            95.0
2  False            96.8
3   True           102.2

## Groupby

In [89]:
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
        'Value': [10, 15, 12, 18, 11, 20],
        'Count': [1, 1, 1, 1, 1, 1]}
df_groupby = pd.DataFrame(data)
print(df_groupby)

  Category  Value  Count
0        A     10      1
1        B     15      1
2        A     12      1
3        B     18      1
4        A     11      1
5        C     20      1

In [90]:
df_groupby_sum = df_groupby.groupby('Category')['Value'].sum()
print(df_groupby_sum)

Category
A    33
B    33
C    20
Name: Value, dtype: int64

In [91]:
df_groupby_count = df_groupby.groupby('Category')['Value'].count()
print(df_groupby_count)

Category
A    3
B    2
C    1
Name: Value, dtype: int64

In [92]:
df_groupby_min_max = df_groupby.groupby('Category')['Value'].agg(['min', 'max'])
print(df_groupby_min_max)

          min  max
Category
A          10   12
B          15   18
C          20   20

In [93]:
df_groupby_mean_two_cols = df_groupby.groupby(['Category', 'Count'])['Value'].mean()
print(df_groupby_mean_two_cols)

Category  Count
A         1        11.0
B         1        16.5
C         1        20.0
Name: Value, dtype: float64

In [94]:
df_groupby_min_max_two_cols = df_groupby.groupby(['Category', 'Count'])['Value'].agg(['min', 'max'])
print(df_groupby_min_max_two_cols)

                min  max
Category Count
A        1       10   12
B        1       15   18
C        1       20   20

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [95]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [96]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [97]:
print(len(a))

457

What is the type of a?

In [98]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>